### model
model_name_or_path: your_path/saves/qwen2_5_vl-3b/spatial/rational_video_dinov3_7B_cross_scan_2/checkpoint-10000
image_max_pixels: 100352
video_max_pixels: 262144
video_fps: 1
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: xlora
freeze_vision_tower: true  # choices: [true, false]
freeze_multi_modal_projector: true  # choices: [true, false]
lora_rank: 8
lora_target: all
flash_attn: fa2

### dataset
dataset: SpaceVista
template: qwen2_vl
cutoff_len: 32768
max_samples: 10000000
overwrite_cache: true
preprocessing_num_workers: 128
# max_length: 262144

### output
output_dir: saves/qwen2_5_vl-3b/spatial/rational_video_expert_full_try_layerwise_0.3
logging_steps: 10
save_steps: 2000
plot_loss: true
overwrite_output_dir: true
save_only_model: false

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 1
learning_rate: 5.0e-6
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

report_to: wandb
run_name: rational_video_expert_full_try_layerwise_0.3 # optional

# geometry_encoder_type: dinov3
# geometry_encoder_path: your_path/dinov3/model